import {KNOT} from '../../physics.js';
import {reachesMark,markExitPath,hasRoundedWaypoint} from '../../course.js';
export function makeRace(course,wind,random=Math.random,laps=2){const rad=wind*Math.PI/180,n={x:Math.cos(rad),z:Math.sin(rad)},a={x:course.at(-1).x,z:course.at(-1).z},b={x:a.x-64*n.z,z:a.z+64*n.x};const lanes=[6,16.4,26.8,37.2,47.6,58];for(let i=lanes.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[lanes[i],lanes[j]]=[lanes[j],lanes[i]]}const starts=lanes.map(lane=>{const lateral=lane+(random()-.5)*2,back=34+random()*16,side=random()<.5?-1:1;return {x:a.x-n.x*back-n.z*lateral,z:a.z-n.z*back+n.x*lateral,heading:rad+side*(45+random()*40)*Math.PI/180,speed:(.6+random()*2.6)*KNOT,startLane:lateral/64}});laps=Math.max(1,Math.min(99,Math.floor(laps)));return {a,b,n,starts,laps,totalMarks:course.length*laps-1,mid:{x:(a.x+b.x)/2,z:(a.z+b.z)/2},remaining:30,stage:'countdown',winner:null,finishOrder:[],elapsed:0}}
export function resetRaceBoat(boat,race,lane=0){const start=race.starts[lane];Object.assign(boat,start);boat.tack=Math.sign(Math.sin(Math.atan2(race.n.z,race.n.x)-boat.heading))||1;Object.assign(boat,{started:false,overEarly:false,finishApproach:false,rounded:0,target:0,lap:1,finished:false,place:null,finishTime:null,exitPath:[],roundPhase:0,roundSide:0,bestDistance:Infinity,progressAt:0,recoverUntil:0,recoveryCount:0,waypointKey:null})}
export function signedLineDistance(race,p){return (p.x-race.a.x)*race.n.x+(p.z-race.a.z)*race.n.z}
export function lineCrossing(race,from,to,upwindOnly=false){const d0=signedLineDistance(race,from),d1=signedLineDistance(race,to),delta=d1-d0;if(Math.abs(delta)<1e-9||d0*d1>0||upwindOnly&&!(d0<=0&&d1>0))return null;const t=-d0/delta;if(t<0||t>1)return null;const x=from.x+(to.x-from.x)*t,z=from.z+(to.z-from.z)*t,dx=race.b.x-race.a.x,dz=race.b.z-race.a.z,u=((x-race.a.x)*dx+(z-race.a.z)*dz)/(dx*dx+dz*dz);return u>=0&&u<=1?t:null}
export function overStartLine(boat,race){const rel=boat.heading-Math.atan2(race.n.z,race.n.x),extent=Math.max(1.1*Math.cos(rel),-3.35*Math.cos(rel))+.73*Math.abs(Math.sin(rel));return signedLineDistance(race,boat)+extent>0;}
export function flagEarlyStarts(race,boats){for(const boat of boats)boat.overEarly=overStartLine(boat,race);}
export function tickRace(race,dt){if(dt<=0||race.stage==='finished')return;race.elapsed+=dt;if(race.stage==='countdown'){race.remaining=Math.max(0,race.remaining-dt);if(race.remaining===0)race.stage='racing'}}
export function raceWaypoint(boat,race){const lane=boat.startLane??.5,t=lane,point={x:race.a.x+(race.b.x-race.a.x)*t,z:race.a.z+(race.b.z-race.a.z)*t};if(boat.finished)return {x:point.x-race.n.x*35,z:point.z-race.n.z*35};if(race.stage==='countdown'){const back=race.remaining>9?25:6;return {x:point.x-race.n.x*back,z:point.z-race.n.z*back}}if(boat.overEarly)return {x:point.x-race.n.x*9,z:point.z-race.n.z*9};if(!boat.started){if(signedLineDistance(race,boat)>0)return {x:point.x-race.n.x*7,z:point.z-race.n.z*7};return {x:point.x+race.n.x*10,z:point.z+race.n.z*10}}if(boat.exitPath?.length)return null;if(boat.rounded>=race.totalMarks){const approach={x:point.x+race.n.x*12,z:point.z+race.n.z*12};if(signedLineDistance(race,boat)<-3)boat.finishApproach=false;if(!boat.finishApproach){if(Math.hypot(boat.x-approach.x,boat.z-approach.z)<4)boat.finishApproach=true;else return approach}return {x:point.x-race.n.x*12,z:point.z-race.n.z*12};}return null}
export function scoreRaceBoat(boat,race,course,from){if(race.stage!=='racing'||boat.finished)return null;if(!boat.started){if(boat.overEarly){if(!overStartLine(boat,race))boat.overEarly=false;return null}if(lineCrossing(race,from,boat,true)!==null){boat.started=true;boat.bestDistance=Infinity;boat.progressAt=boat.clock||0}return null}if(boat.rounded>=race.totalMarks){if(boat.exitPath?.length)return null;const cross=lineCrossing(race,from,boat);if(cross!==null){boat.finished=true;return cross}return null}const mark=course[boat.target],next=course[(boat.target+1)%course.length];if(!boat.exitPath?.length&&(!boat.skill||hasRoundedWaypoint(mark,next,boat))&&reachesMark(mark,from,boat,next)){boat.rounded++;boat.lap=Math.min(race.laps,Math.floor(boat.rounded/course.length)+1);boat.target=boat.rounded%course.length;boat.exitPath=boat.skill?markExitPath(mark,next,boat):[];boat.roundPhase=0;boat.roundSide=0;boat.bestDistance=Infinity;boat.progressAt=boat.clock||0}return null}
export function raceTarget(boat,race,course){if(!boat.started||race.stage==='countdown')return {...race.mid,color:'#e5f6ff',name:'Start line'};if(boat.rounded>=race.totalMarks)return {...race.mid,color:'#ffdb32',name:'Finish line'};return course[boat.target]}
export function raceStatus(boat,race,course){return boat.overEarly?'OCS · Return behind line, then recross':boat.place?`${boat.place}${['','st','nd','rd','th','th','th'][boat.place]} place${boat.finished?' · Finished':' · Remaining boat'}`:!boat.started?`Lap 1/${race.laps} · Start line`:`Lap ${boat.lap}/${race.laps} · ${boat.rounded>=race.totalMarks?'Finish line':course[boat.target].name.split(' · ').at(-1)}`}

export function recordFinishes(race,finishes,boats,dt=0){for(const {body,fraction}of finishes.sort((a,b)=>a.fraction-b.fraction)){if(body.place)continue;body.place=race.finishOrder.length+1;body.finishTime=Math.max(0,race.elapsed-30-dt+fraction*dt);race.finishOrder.push(body.name);race.winner ||= body.name;}if(race.finishOrder.length>=boats.length-1){race.stage='finished';for(const body of boats)if(!body.place)body.place=boats.length;}}

export function lineVisible(race,boats){return race.stage==='countdown'||race.stage==='finished'||boats.some(b=>!b.started)||boats.some(b=>b.rounded>=race.totalMarks)}
export function formatRaceTime(seconds){const tenths=Math.round(Math.max(0,seconds)*10),minutes=Math.floor(tenths/600);return `${minutes}:${String(Math.floor(tenths/10)%60).padStart(2,'0')}.${tenths%10}`}
export function raceResults(race,boats){return [...boats].sort((a,b)=>a.place-b.place).map(b=>({place:b.place,name:b.name,time:formatRaceTime(b.finishTime??Math.max(0,race.elapsed-30)),finished:b.finished}));}

export function countdownPath(seconds){const fraction=Math.max(0,Math.min(1,seconds/30));if(fraction===0)return 'M50 50';if(fraction===1)return 'M50 50 L50 6 A44 44 0 1 1 50 94 A44 44 0 1 1 50 6 Z';const angle=fraction*2*Math.PI,x=50+44*Math.sin(angle),y=50-44*Math.cos(angle);return `M50 50 L50 6 A44 44 0 ${fraction>.5?1:0} 1 ${x} ${y} Z`; }
