import {createMooringView,startMooringMusic} from './moorings.js';
import {DAYLIGHT,createAtmosphere,createBoatEffects,addPassingLife,addNavigationLights} from './eye-candy.js';
import {createRaceHistory,HISTORY_BOATS} from './race-history.js';
import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {advanceBoat,boatBob,noGoHalfAngle,trimHint,KNOT,MIN_SPEED,waterSpeedGain,windDialRotation,relativeWind,tillerInput,steerHeading,telltaleState} from './physics.js';
import {leadingEdge,swingVertex} from './sail-shape.js';
import {makeCourse,COURSE_TYPES,MARK_RADIUS,markBearing,reachesMark,nextMark,roundingNormal} from './course.js';
import {createRacer,RACER_PROFILES,stepRacer,bumpBoats,bumpMark,windShadow} from './racers.js';
import {windPatches,sampleWind} from './wind-field.js';
import {makeRace,resetRaceBoat,flagEarlyStarts,tickRace,raceWaypoint,scoreRaceBoat,raceTarget,raceStatus,recordFinishes,lineVisible,raceResults,formatRaceTime,countdownPath} from './race.js';
import {addYachtClub,updateYachtClubWind,createPuffVisuals,addCommitteeBoat,addCoastalLandmarks} from './scenery.js';
import {createCourseMap} from './course-map.js';
import {installWaterOcclusion} from './water-mask.js';
const $=id=>document.getElementById(id), tillerPad=$('tillerPad'), host=$('scene');
const renderer=new THREE.WebGLRenderer({antialias:true,stencil:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x97bdcd);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.prepend(renderer.domElement);
let historyStorage;try{historyStorage=window.localStorage}catch{}const finishHistory=createRaceHistory(historyStorage);
let courseChoice='starboard';const courseNames={starboard:'Starboard triangle',port:'Port triangle',updown:'Upwind/downwind','long-starboard':'Long starboard','long-port':'Long port','long-updown':'Long upwind/downwind'};let meanBearing=70,meanStrength=12;let raceLaps=2;try{const saved=Number(window.localStorage?.getItem('regatta-laps'));if(Number.isInteger(saved)&&saved>=1&&saved<=99)raceLaps=saved}catch{}
const navigationLights=[];function updateNavigationLights(){for(const lights of navigationLights)lights.visible=timeOfDay==='night'}
let timeOfDay='midday';try{const saved=window.localStorage?.getItem('regatta-daylight');if(DAYLIGHT[saved])timeOfDay=saved}catch{}
let mooringMode=false,mooringView=null,mooringTime=0,mooringMusic=null,mooringMusicEnabled=true;
let finishCelebrated=false;const confetti=document.createElement('div');confetti.className='finish-confetti';confetti.setAttribute('aria-hidden','true');for(let i=0;i<64;i++){const piece=document.createElement('i');piece.style.setProperty?.('--x',`${(i*37)%100}%`);piece.style.setProperty?.('--delay',`${i%9*.06}s`);piece.style.setProperty?.('--drift',`${(i%7-3)*35}px`);piece.style.background=['#ffe16c','#ff8176','#60e1d9','#bba5ff'][i%4];confetti.append(piece)}host.append(confetti);
let startAudio=null,soundEnabled=true;
function armStartAudio(event){if(event?.target?.id==='startSound')return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;startAudio ||= new Audio();Promise.resolve(startAudio.resume()).then(()=>{$('startSound').textContent=soundEnabled?'Sound on':'Sound off'}).catch(()=>{});}catch{}}
function playStartingGun(){if(!soundEnabled||!startAudio||startAudio.state!=='running')return;const audio=startAudio,t=audio.currentTime,buffer=audio.createBuffer(1,Math.ceil(audio.sampleRate*.9),audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const sec=i/audio.sampleRate;data[i]=(Math.random()*2-1)*Math.exp(-sec*9)}const noise=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();noise.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(3200,t);filter.frequency.exponentialRampToValueAtTime(500,t+.7);gain.gain.setValueAtTime(.38,t);noise.connect(filter);filter.connect(gain);gain.connect(audio.destination);noise.start(t);const bass=audio.createOscillator(),low=audio.createGain();bass.type='sine';bass.frequency.setValueAtTime(130,t);bass.frequency.exponentialRampToValueAtTime(42,t+.45);low.gain.setValueAtTime(.28,t);low.gain.exponentialRampToValueAtTime(.001,t+.65);bass.connect(low);low.connect(audio.destination);bass.start(t);bass.stop(t+.7);}
document.addEventListener('pointerdown',armStartAudio,{capture:true});document.addEventListener('keydown',armStartAudio,{capture:true});$('startSound').addEventListener('click',()=>{soundEnabled=startAudio?.state==='running'?!soundEnabled:true;armStartAudio();$('startSound').textContent=soundEnabled?'Sound on':'Sound off';$('startSound').setAttribute('aria-pressed',String(soundEnabled))});
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x97bdcd,150,650);
const camera=new THREE.PerspectiveCamera(78,1,.1,1200);const cameraTarget=new THREE.Vector3(-1,2.8,0);let orbitAngle=0,orbitDragging=false,orbitX=0,heading=0,tiller=0,running=false,simTime=0;
function updateCamera(){camera.position.set(cameraTarget.x-9.5*Math.cos(heading-orbitAngle),1.65,cameraTarget.z-9.5*Math.sin(heading-orbitAngle));camera.lookAt(cameraTarget)}updateCamera();
const ambient=new THREE.HemisphereLight(0xe4f6ff,0x496673,2.4);scene.add(ambient);const sun=new THREE.DirectionalLight(0xfff6dd,3);sun.position.set(-4,10,7);scene.add(sun);const atmosphere=createAtmosphere(scene,renderer,sun,ambient);atmosphere.set(timeOfDay);const boatEffects=createBoatEffects(scene),updatePassingLife=addPassingLife(scene);
// Fixed terrain landmarks provide visual bearings as the boat moves and turns.
function makeIsland(x,z,width,depth,height,seed,biome=0){
 const geo=new THREE.PlaneGeometry(width,depth,36,24);geo.rotateX(-Math.PI/2);const p=geo.attributes.position,colors=[];
 const palette=[[0x203f49,0x486350],[0xc88a4c,0x925433],[0xe2c17c,0x39824e],[0xba632e,0xe5a75c]][biome];const low=new THREE.Color(palette[0]),high=new THREE.Color(palette[1]);
 for(let i=0;i<p.count;i++){const xx=p.getX(i),zz=p.getZ(i),a=Math.atan2(zz/depth,xx/width),r=Math.hypot(xx/(width*.5),zz/(depth*.5));const shore=1+.1*Math.sin(a*3+seed)+.05*Math.cos(a*7-seed);const mound=Math.max(0,1-r/shore);const h=height*mound**1.25*(.78+.15*Math.sin(xx*.10+seed)+.07*Math.cos(zz*.19));p.setY(i,.025+h);const c=low.clone().lerp(high,Math.min(1,h/height));colors.push(c.r,c.g,c.b)}
 geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const island=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,side:THREE.DoubleSide}));island.position.set(x,0,z);scene.add(island);
}
[[260,-180,120,65,27,1],[320,70,95,70,19,2],[180,290,160,85,32,3],[-140,310,115,70,24,4],[-300,100,140,80,35,5],[-230,-230,100,60,18,6],[25,-340,170,90,29,7],[230,-350,100,65,22,8,1],[-360,-65,110,65,26,9,3],[360,220,135,80,30,10,2],[-85,-240,70,45,14,11,2],[100,380,130,80,33,12,1],[-310,290,125,75,27,13,3]].forEach(v=>makeIsland(...v));
const yachtClub=addYachtClub(scene);const updatePuffs=createPuffVisuals(scene);
const updateCoast=addCoastalLandmarks(scene);makeIsland(140,235,100,75,8,14,2);makeIsland(-350,-300,125,80,22,15,1);
const updateCourseMap=createCourseMap($('courseMap'));
const boat=new THREE.Group();scene.add(boat);const playerRace={name:'You',target:0,rounded:0,lap:1,started:false,exitPath:[],heading:0};const fleet=[];let collisionUntil=0,collisionMessage='';
function setControlsOpen(open){$('settingsPanel').classList.toggle('is-open',open);$('settingsToggle').setAttribute('aria-expanded',String(open));if(open){running=false;stop()}}
$('settingsToggle').addEventListener('click',()=>setControlsOpen($('settingsToggle').getAttribute('aria-expanded')!=='true'));$('settingsClose').addEventListener('click',()=>setControlsOpen(false));
function cloneMaterial(m){const c=m.clone();c.onBeforeCompile=m.onBeforeCompile;c.customProgramCacheKey=m.customProgramCacheKey;return c}
function createFleet(){for(const profile of RACER_PROFILES){const r=createRacer(profile.skill);resetRaceBoat(r,race,fleet.length+1);r.root=boat.clone(true);r.root.traverse(o=>{if(o.isMesh){o.material=Array.isArray(o.material)?o.material.map(cloneMaterial):cloneMaterial(o.material);for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m.name==='WHITE')m.color.set(r.color)}});r.sail=r.root.getObjectByName('Sail');r.sail.geometry=r.sail.geometry.clone();installSailBadge(r.sail,r.badge);r.boom=r.root.getObjectByName('Boom');r.tag=document.createElement('div');r.tag.className='racer-tag';r.tag.textContent=r.name;r.tag.style.borderColor=r.hex;host.append(r.tag);r.sheetLine=sheetLine.clone();r.sheetLine.geometry=sheetLine.geometry.clone();r.sheetLine.visible=true;scene.add(r.sheetLine);scene.add(r.root);fleet.push(r)}}
function resetFleet(){collisionUntil=0;collisionMessage='';for(const r of fleet){Object.assign(r,createRacer(r.skill));resetRaceBoat(r,race,fleet.indexOf(r)+1);}}
function updateWindShadows(wind){const player={x:boat.position.x,z:boat.position.z,heading};const bodies=[player,...fleet];for(const r of fleet)r.shadow=windShadow(r,bodies,wind);return windShadow(player,bodies,wind)}
function stepFleet(s,dt){const traffic=[{x:boat.position.x,z:boat.position.z,heading,speed,sailAngle:angle},...fleet.map(r=>({...r,isAI:true}))];for(const r of fleet){const local=sampleWind(s.baseDirection,s.baseStrength,simTime,r.x,r.z,s.patches);stepRacer(r,course,local.direction,local.strength,simTime,dt,traffic,{score:false,gust:local.gust,waypoint:raceWaypoint(r,race),obstacles:[...course,...(lineVisible(race,[playerRace,...fleet])?[{...race.b,radius:3.8}]:[])]})}if(dt>0){const player={x:boat.position.x,z:boat.position.z,heading,speed,sailAngle:angle},bodies=[player,...fleet],faults=new Map();let impact=false;
 for(let pass=0;pass<3;pass++){for(let i=0;i<bodies.length;i++){for(let j=i+1;j<bodies.length;j++){const key=`${i}-${j}`,hit=bumpBoats(bodies[i],bodies[j],s.direction,faults.get(key),!faults.has(key));if(hit){faults.set(key,hit);if(i===0){impact=true;collisionMessage=hit.offender===player?`Your penalty · ${hit.reason}`:`Other boat penalized · ${hit.reason}`}}}for(const m of [...course,...(lineVisible(race,[playerRace,...fleet])?[{...race.b,radius:3.8}]:[])]){if(bumpMark(bodies[i],m)&&i===0){impact=true;collisionMessage='Buoy contact · speed penalty'}}}}
 boat.position.x=player.x;boat.position.z=player.z;speed=player.speed;if(impact)collisionUntil=simTime+2.2;}

 for(const [index,r] of fleet.entries()){r.sail.visible=!orbitDragging;r.root.position.set(r.x,boatBob(simTime+index*.65),r.z);r.root.rotation.order='YXZ';r.root.rotation.set(r.heel*Math.PI/180,-r.heading,0,'YXZ');const p=r.sail.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=swingVertex(sailOriginal[i*3],sailOriginal[i*3+1],sailOriginal[i*3+2],sailPivots[i],r.angle*Math.PI/180);p.setXYZ(i,...v)}p.needsUpdate=true;r.sail.geometry.computeBoundingSphere();updateSailFlutter(r.sail,r.angle,r.motion?.sail.status,index*.7);r.sail.material.color.set(r.shadow>.06?0xffe44d:0xfafaf3).multiplyScalar(timeOfDay==='night'?.28:1);r.boom.rotation.y=r.angle*Math.PI/180;r.root.updateMatrixWorld(true);updateSheets(r.root,r.sheetLine);const pos=r.root.localToWorld(new THREE.Vector3(-1,6.6,0)).project(camera);r.tag.hidden=pos.z>1||pos.z<-1||Math.abs(pos.x)>1||Math.abs(pos.y)>1;r.tag.style.left=`${(pos.x*.5+.5)*host.clientWidth}px`;r.tag.style.top=`${(-pos.y*.5+.5)*host.clientHeight}px`;}
 $('impactStatus').textContent=simTime<collisionUntil?collisionMessage:'';
}
let course=makeCourse(70),activeMark=0,marksRounded=0,race=makeRace(course,70,Math.random,raceLaps);
resetRaceBoat(playerRace,race,0);boat.position.set(playerRace.x,0,playerRace.z);heading=playerRace.heading;cameraTarget.set(playerRace.x-Math.cos(heading),2.8,playerRace.z-Math.sin(heading));updateCamera();
const committee=addCommitteeBoat(scene),startLineGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),startLine=new THREE.Line(startLineGeo,new THREE.LineDashedMaterial({color:0xffffff,dashSize:1.4,gapSize:1.2}));scene.add(startLine);
function updateStartLine(){race.lineVisible=lineVisible(race,[playerRace,...fleet]);committee.visible=startLine.visible=race.lineVisible;committee.position.set(race.b.x,boatBob(simTime),race.b.z);committee.rotation.y=-Math.atan2(race.n.z,race.n.x);startLineGeo.setFromPoints([new THREE.Vector3(race.a.x,.16,race.a.z),new THREE.Vector3(race.b.x,.16,race.b.z)]);startLine.computeLineDistances();startLine.material.color.set(race.stage==='countdown'?0xff6d61:0xffffff)}updateStartLine();
function resetRace(){race=makeRace(course,meanBearing,Math.random,raceLaps);resetRaceBoat(playerRace,race,0);boat.position.set(playerRace.x,0,playerRace.z);heading=playerRace.heading;speed=playerRace.speed;resetFleet();updateStartLine()}
function updateRaceBoard(){if(playerRace.finished&&!finishCelebrated){finishCelebrated=true;confetti.classList.add('celebrate')}updateResults();$('countdownDial').style.display=race.stage==='countdown'?'block':'none';$('countdownPie').setAttribute('d',countdownPath(race.remaining));$('countdownTime').textContent=String(Math.ceil(race.remaining));$('lapTitle').textContent=` ${courseNames[course.layout]} · ${race.laps} LAP${race.laps===1?'':'S'}`;$('lapCourseText').textContent=`30-second start between yellow and the committee boat. Sail ${race.laps} lap${race.laps===1?'':'s'}: ${course.length===2?'orange → yellow':'orange → maroon → yellow'}. On the last lap, finish between yellow and the committee boat.`;const racers=[playerRace,...fleet];for(const [i,r]of racers.entries())$(['playerScore','expertScore','weekendScore','noviceScore','marqueeScore','scopeScore'][i]).textContent=`${r.name} · ${raceStatus(r,race,course)} · ${r.rounded} marks`;$('raceBanner').classList.toggle('player-finished',playerRace.finished);$('raceBanner').classList.toggle('early-start',playerRace.overEarly);$('raceStatus').textContent=playerRace.finished?`YOU FINISHED · ${playerRace.place}${['','st','nd','rd','th','th','th'][playerRace.place]} PLACE · ${formatRaceTime(playerRace.finishTime)}${race.stage==='finished'?'':' · Waiting for the remaining finishers'}`:playerRace.overEarly?'EARLY START · Get fully behind the line, then recross':race.stage==='finished'?`RESULTS · ${[...racers].sort((a,b)=>a.place-b.place).map(r=>`${r.place}. ${r.name}`).join(' · ')} · Restart race` : race.winner?`${race.winner} finished first · Racing for the remaining places`:race.stage==='countdown'?`START IN ${Math.ceil(race.remaining)} · Be behind the line at the gun`:`RACING · ${race.laps} LAP${race.laps===1?'':'S'}`;}

const buoys=course.map(mark=>{const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:mark.color,roughness:.6,emissive:mark.color,emissiveIntensity:.12});const cone=new THREE.Mesh(new THREE.ConeGeometry(1.05,2.8,24),mat);cone.position.y=1.55;group.add(cone);const band=new THREE.Mesh(new THREE.TorusGeometry(.8,.12,8,24),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.7}));band.rotation.x=Math.PI/2;band.position.y=.58;group.add(band);scene.add(group);group.position.set(mark.x,0,mark.z);const arc=new THREE.Mesh(new THREE.RingGeometry(1.85,MARK_RADIUS,40,1,-Math.PI/2,Math.PI),new THREE.MeshBasicMaterial({color:mark.color,side:THREE.DoubleSide,transparent:true,opacity:.15,depthWrite:false}));arc.rotation.order='YXZ';arc.rotation.x=-Math.PI/2;arc.position.set(mark.x,.14,mark.z);group.userData.arc=arc;scene.add(arc);return group});
function updateRoundingArcs(){course.forEach((mark,i)=>{const n=roundingNormal(mark,course[nextMark(i,course.length)]),arc=buoys[i].userData.arc;arc.position.set(mark.x,.14,mark.z);arc.rotation.y=-Math.atan2(n.z,n.x);arc.material.opacity=i===activeMark?.34:.10})}updateRoundingArcs();
function resetCourse(){course=makeCourse(meanBearing,courseChoice);activeMark=0;marksRounded=0;buoys.forEach((buoy,i)=>{const mark=course[i];buoy.visible=buoy.userData.arc.visible=Boolean(mark);if(mark){buoy.position.set(mark.x,0,mark.z);buoy.children[0].material.color.set(mark.color);buoy.children[0].material.emissive.set(mark.color);buoy.userData.arc.material.color.set(mark.color)}});updateRoundingArcs();}
function updateMarkDial(){updateRoundingArcs();const target=raceTarget(playerRace,race,course),bearing=markBearing(target,boat.position.x,boat.position.z,heading);$('markDialArrow').setAttribute('transform',`rotate(${bearing} 50 50)`);$('markDialArrow').style.color=target.color;$('markDialLabel').textContent=target.name;$('markDialLabel').style.color=target.color;$('markDistance').textContent=`${Math.hypot(target.x-boat.position.x,target.z-boat.position.z).toFixed(0)} m · rounded ${marksRounded}`;buoys.forEach((b,i)=>{b.children[0].material.emissiveIntensity=i===activeMark?.3:.05})}
const ribbons=[-1,1].map(side=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(10*6*3),3));const mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:side<0?0xff3558:0x24d975,side:THREE.DoubleSide}));scene.add(mesh);mesh.visible=false;return {side,mesh}});
let waterOffsetX=0,waterOffsetZ=0;let speed=playerRace.speed,travel=0,seaSurface,sailEdge;let sail,boom,aftPulley,forwardPulley,sailOriginal,sailPivots,angle=0,heel=0,ready=false,trimIn=false,trimOut=false,lastTime=performance.now();
const lineGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(),new THREE.Vector3(),new THREE.Vector3()]);const sheetLine=new THREE.LineSegments(lineGeo,new THREE.LineBasicMaterial({color:0xdcb974}));scene.add(sheetLine);sheetLine.visible=false;
function installSailBadge(mesh,index){const p=mesh.geometry.attributes.position,uv=[],weights=[];const flutter={flutterTime:{value:0},flutterAmount:{value:0},flutterAngle:{value:0}};mesh.userData.flutter=flutter;for(let i=0;i<p.count;i++){const y=sailOriginal[i*3+1],distance=(sailPivots?.[i]??sailEdge(y))-sailOriginal[i*3];weights.push(Math.min(1,Math.max(0,distance)/1.6)*Math.min(1,Math.max(0,y-1.25)/.65))}mesh.geometry.setAttribute('flutterWeight',new THREE.Float32BufferAttribute(weights,1));for(let i=0;i<p.count;i++)uv.push((sailOriginal[i*3]+1.02)/.48,(sailOriginal[i*3+1]-3.35)/.48);mesh.geometry.setAttribute('badgeUv',new THREE.Float32BufferAttribute(uv,2));const inks=['vec3(.72,.025,.065)','vec3(.025,.23,.72)','vec3(.8,.5,.015)','vec3(.035,.48,.15)','vec3(.035,.045,.055)','vec3(.25,.32,.38)'];const symbols=['step(abs(q.x-q.y*.65),.14)*step(abs(q.y),.55)','max(step(abs(q.x),.13)*step(abs(q.y),.55),step(abs(q.y),.13)*step(abs(q.x),.55))','step(abs(abs(q.x)+abs(q.y)-.50),.12)','step(abs(q.y),.48)*max(step(abs(q.x+.34),.10),max(step(abs(q.x),.10),step(abs(q.x-.34),.10)))','max(step(abs(q.x-q.y),.11),step(abs(q.x+q.y),.11))*step(length(q),.55)','step(abs(length(q)-.4),.10)+step(length(q),.12)'];mesh.material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,flutter);shader.vertexShader='attribute float flutterWeight;uniform float flutterTime;uniform float flutterAmount;uniform float flutterAngle;attribute vec2 badgeUv;varying vec2 sailBadge;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nsailBadge=badgeUv;\nfloat ripple=sin(position.y*6.0+flutterTime*17.0)*flutterWeight*flutterAmount;transformed.x+=sin(flutterAngle)*ripple;transformed.z+=cos(flutterAngle)*ripple;');shader.fragmentShader='varying vec2 sailBadge;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>\nvec2 q=sailBadge;float disk=1.0-smoothstep(.90,.94,length(q));float ring=step(.76,length(q))*disk;float symbol=(${symbols[index]})*disk;diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.98),disk*.95);diffuseColor.rgb=mix(diffuseColor.rgb,${inks[index]},max(ring,symbol));`);};mesh.material.customProgramCacheKey=()=>`sail-badge-${index}`;mesh.material.needsUpdate=true;}
function updateSailFlutter(mesh,sailAngle,status,offset=0){const f=mesh.userData.flutter;f.flutterTime.value=simTime+offset;f.flutterAngle.value=sailAngle*Math.PI/180;f.flutterAmount.value=status==='Luffing'?.095:status==='Running'?.035:.014;}
function updateSheets(root,line){
 root.updateMatrixWorld(true);const b=root.getObjectByName('Boom'),aft=root.getObjectByName('Pulley003'),front=root.getObjectByName('Pulley');
 const points=[aft?aft.localToWorld(new THREE.Vector3(.0558,-.0843,0)):b.localToWorld(new THREE.Vector3(-2.7403,-.0894,0)),root.localToWorld(new THREE.Vector3(-2.6,.33,0)),front?front.localToWorld(new THREE.Vector3(.0607,-.0808,0)):b.localToWorld(new THREE.Vector3(-.3655,-.0973,0)),root.localToWorld(new THREE.Vector3(-1.28,.32,0))];
 const p=line.geometry.attributes.position;points.forEach((v,i)=>p.setXYZ(i,v.x,v.y,v.z));p.needsUpdate=true;line.geometry.computeBoundingSphere();
}
function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
new GLTFLoader().load('./assets/Laser.glb',g=>{
 scene.add(g.scene);g.scene.updateMatrixWorld(true);const hull=g.scene.getObjectByName('Hull');sail=g.scene.getObjectByName('Sail');boom=g.scene.getObjectByName('Boom');
 if(!hull||!sail||!boom)throw new Error('Missing Hull, Sail, or Boom');aftPulley=g.scene.getObjectByName('Pulley003');forwardPulley=g.scene.getObjectByName('Pulley');boat.add(hull);
 // The source GLB has only the negative-Z half of the hull/deck.
 // Mirror just those surfaces, without duplicating mast, sail, or fittings.
 const halfHullMeshes=[];
 hull.traverse(o=>{if(o.isMesh){o.geometry.computeBoundingBox();const b=o.geometry.boundingBox;if(b.max.x-b.min.x>4 && b.min.z<-.5 && b.max.z<.0001)halfHullMeshes.push(o)}});
 for(const original of halfHullMeshes){
  const mirrored=original.clone(false);mirrored.name=original.name+'_mirrored';
  mirrored.geometry=original.geometry.clone();mirrored.geometry.applyMatrix4(new THREE.Matrix4().makeScale(1,1,-1));
  const index=mirrored.geometry.index;
  if(index){for(let i=0;i<index.count;i+=3){const a=index.getX(i);index.setX(i,index.getX(i+2));index.setX(i+2,a)}index.needsUpdate=true}
  else {mirrored.geometry=mirrored.geometry.toNonIndexed();const attrs=mirrored.geometry.attributes;for(const attr of Object.values(attrs)){for(let i=0;i<attr.count;i+=3){for(let c=0;c<attr.itemSize;c++){const a=attr.array[i*attr.itemSize+c];attr.array[i*attr.itemSize+c]=attr.array[(i+2)*attr.itemSize+c];attr.array[(i+2)*attr.itemSize+c]=a}}attr.needsUpdate=true}}
  mirrored.geometry.computeBoundingBox();mirrored.geometry.computeBoundingSphere();original.parent.add(mirrored);mirrored.userData.waterHull=true;
 }
 const strayBoard=g.scene.getObjectByName('Cube');if(strayBoard)strayBoard.removeFromParent();
 scene.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.side=THREE.DoubleSide;if(m.map){m.map.colorSpace=THREE.SRGBColorSpace;m.map.anisotropy=renderer.capabilities.getMaxAnisotropy()}m.needsUpdate=true}}});
 sail.geometry=sail.geometry.clone();sail.geometry.computeVertexNormals();
 sail.material=new THREE.MeshBasicMaterial({color:0xfafaf3,side:THREE.DoubleSide});
 const sailPos=sail.geometry.attributes.position;sailOriginal=sailPos.array.slice();
 const edge=leadingEdge(Array.from({length:sailPos.count},(_,i)=>[sailPos.getX(i),sailPos.getY(i)]));
 sailEdge=edge;installSailBadge(sail,0);sailPivots=Array.from({length:sailPos.count},(_,i)=>edge(sailPos.getY(i)));
 hull.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)if(m.name==='WHITE'){m.color.set(0xb71e2b);m.roughness=.32;m.metalness=0;m.needsUpdate=true}}});
 const sea=g.scene.getObjectByName('Sea');seaSurface=sea;if(sea){
  const n=128,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=(y*n+x)*4;data[i]=128+Math.round(38*Math.sin(x*Math.PI*8/n+y*Math.PI*4/n));data[i+1]=128+Math.round(30*Math.cos(y*Math.PI*12/n-x*Math.PI*4/n));data[i+2]=245;data[i+3]=255}
  const ripple=new THREE.DataTexture(data,n,n,THREE.RGBAFormat);ripple.wrapS=ripple.wrapT=THREE.RepeatWrapping;ripple.repeat.set(180,180);ripple.needsUpdate=true;
  sea.material=new THREE.MeshStandardMaterial({color:0x087dae,roughness:.24,metalness:.18,normalMap:ripple,normalScale:new THREE.Vector2(.44,.44),side:THREE.DoubleSide});
  sea.material.userData.waterTime={value:0};
  sea.material.onBeforeCompile=shader=>{shader.uniforms.waterTime=sea.material.userData.waterTime;shader.vertexShader='varying vec3 waterWorld;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nwaterWorld=(modelMatrix*vec4(position,1.0)).xyz;');shader.fragmentShader='uniform float waterTime;\nvarying vec3 waterWorld;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat swell=sin(waterWorld.x*.32+waterWorld.z*.17-waterTime*1.3)*sin(waterWorld.z*.43-waterTime*.8);\nfloat crest=pow(max(0.0,sin(waterWorld.x*1.9+waterWorld.z*.8-waterTime*2.1)),18.0)*pow(max(0.0,sin(waterWorld.z*2.4+waterWorld.x*.25-waterTime*1.6)),6.0);\ndiffuseColor.rgb*=1.0+swell*.11;\ndiffuseColor.rgb=mix(diffuseColor.rgb,vec3(.30,.68,.78),crest*.40);');};
  const waterHulls=[];hull.traverse(o=>{if(halfHullMeshes.includes(o)||o.userData.waterHull)waterHulls.push(o)});installWaterOcclusion(waterHulls,sea);
 }
 createFleet();for(const root of [boat,...fleet.map(r=>r.root)])navigationLights.push(addNavigationLights(root));updateNavigationLights();$('loading').hidden=true;ready=true;sheetLine.visible=true;
},undefined,()=>{$('loading').textContent='The boat could not load. Reload this page to try again.'});
function state(){return {direction:meanBearing,strength:meanStrength,sheet:Number($('sheet').value)}}
function labels(){const s=state();const bearing=((s.direction%360)+360)%360;$('sheetOut').textContent=`${Math.round(s.sheet)}°`;$('windTag').textContent=`TRUE WIND FROM ${bearing.toFixed(0).padStart(3,'0')}°`;}
const mobileTrim=$('mobileTrim');let touchTillerId=null,mobileTrimId=null;
const mobileControls=()=>window.matchMedia?.('(max-width: 740px), (pointer: coarse)').matches??false;
function touchRunning(){if(mooringMode){running=false;return}running=(touchTillerId!==null||mobileTrimId!==null)&&!document.hidden;tillerPad.classList.toggle('active',running)}
function pointerPosition(e){if(mooringMode)return;if(orbitDragging)return;if(e.pointerType==='touch'&&mobileControls()){if(e.pointerId!==touchTillerId)return;const b=tillerPad.getBoundingClientRect();tiller=tillerInput(THREE.MathUtils.clamp((e.clientX-b.left)/b.width,0,1));touchRunning();return;}const b=tillerPad.getBoundingClientRect();const inside=e.clientX>=b.left&&e.clientX<b.right&&e.clientY>=b.top&&e.clientY<b.bottom;running=inside&&!document.hidden;tillerPad.classList.toggle('active',running);if(!inside){releaseTrim();return}if(!orbitDragging)tiller=tillerInput((e.clientX-b.left)/b.width);}
tillerPad.addEventListener('pointerenter',pointerPosition);tillerPad.addEventListener('pointerleave',e=>{if(orbitDragging||e.pointerType==='touch'&&mobileControls())return;running=false;tillerPad.classList.remove('active');releaseTrim()});window.addEventListener('pointermove',pointerPosition);window.addEventListener('blur',()=>{running=false;stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden){running=false;stop()}});

$('sheet').addEventListener('input',labels);$('strength').addEventListener('input',()=>{$('strengthOut').textContent=`${$('strength').value} kn`});
function releaseTrim(){trimIn=false;trimOut=false;$('in').classList.remove('active');$('out').classList.remove('active');$('mobileTrimIn').classList.remove('active');$('mobileTrimOut').classList.remove('active')}
function setSailsVisible(visible){if(sail)sail.visible=visible;for(const r of fleet)r.sail.visible=visible}
function stop(){if(touchTillerId!==null||mobileTrimId!==null){touchTillerId=null;mobileTrimId=null;tiller=0;touchRunning()}if(orbitDragging){orbitAngle=0;updateCamera()}orbitDragging=false;setSailsVisible(true);releaseTrim()}
function hold(which,on){if(which==='in')trimIn=on;else trimOut=on;$(which).classList.toggle('active',on)}
for(const which of ['in','out']){$(which).addEventListener('pointerdown',e=>{e.preventDefault();$(which).setPointerCapture(e.pointerId);hold(which,true)});$(which).addEventListener('pointerup',()=>hold(which,false));$(which).addEventListener('pointercancel',stop)}
function moveThumbTrim(e){if(e.pointerId!==mobileTrimId)return;e.preventDefault();const b=mobileTrim.getBoundingClientRect(),offset=e.clientY-(b.top+b.height/2);const which=offset<-7?'in':offset>7?'out':null;hold('in',which==='in');hold('out',which==='out');$('mobileTrimIn').classList.toggle('active',which==='in');$('mobileTrimOut').classList.toggle('active',which==='out');touchRunning()}
mobileTrim.addEventListener('pointerdown',e=>{if(!mobileControls()||mobileTrimId!==null)return;e.preventDefault();mobileTrimId=e.pointerId;mobileTrim.setPointerCapture(e.pointerId);moveThumbTrim(e)});
mobileTrim.addEventListener('pointermove',moveThumbTrim);
function endThumbTrim(e){if(e.pointerId!==mobileTrimId)return;mobileTrimId=null;releaseTrim();touchRunning()}
for(const event of ['pointerup','pointercancel','lostpointercapture'])mobileTrim.addEventListener(event,endThumbTrim);
function endTouchTiller(e){if(e.pointerId!==touchTillerId)return;touchTillerId=null;tiller=0;touchRunning()}
tillerPad.addEventListener('lostpointercapture',endTouchTiller);
for(const surface of [renderer.domElement,tillerPad]){
 surface.addEventListener('contextmenu',e=>e.preventDefault());surface.addEventListener('pointerdown',e=>{if(mooringMode)return;if(e.pointerType==='touch'&&mobileControls()){if(surface===tillerPad&&touchTillerId===null){e.preventDefault();touchTillerId=e.pointerId;surface.setPointerCapture(e.pointerId);pointerPosition(e)}return}if(e.button===1){e.preventDefault();orbitDragging=true;tiller=0;releaseTrim();setSailsVisible(false);for(const r of ribbons)r.mesh.visible=false;orbitX=e.clientX;surface.setPointerCapture(e.pointerId);return}if(surface===tillerPad&&(e.button===0||e.button===2)){e.preventDefault();surface.setPointerCapture(e.pointerId);hold(e.button===0?'in':'out',true)}});
 surface.addEventListener('pointermove',e=>{if(orbitDragging){orbitAngle+=(e.clientX-orbitX)*.008;orbitX=e.clientX;updateCamera()}});surface.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});surface.addEventListener('pointerup',e=>{if(e.pointerType==='touch'&&mobileControls()){endTouchTiller(e);return}stop();orbitAngle=0;updateCamera();pointerPosition(e)});surface.addEventListener('pointercancel',e=>{if(e.pointerType==='touch'&&mobileControls()){endTouchTiller(e);return}stop();orbitAngle=0;updateCamera()});
}
window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('keydown',e=>{if(e.target.matches('input,button'))return;if(e.key.toLowerCase()==='a')hold('in',true);if(e.key.toLowerCase()==='d')hold('out',true)});window.addEventListener('keyup',e=>{if(['a','d'].includes(e.key.toLowerCase()))stop()});
function restartGame(){leaveMoorings();stop();boatEffects.reset();finishCelebrated=false;confetti.classList.remove('celebrate');waterOffsetX=0;waterOffsetZ=0;speed=MIN_SPEED;travel=0;heading=0;tiller=0;simTime=0;boat.position.set(0,0,0);cameraTarget.set(-1,2.8,0);orbitAngle=0;updateCamera();meanBearing=70;$('sheet').value=40;labels();resetCourse();resetRace();updateMarkDial();updateResults()}
function openRaceSetup(){running=false;stop();$('timeOfDay').value=timeOfDay;$('courseType').value=courseChoice;$('lapCount').value=String(raceLaps);$('strength').value=String(meanStrength);$('strengthOut').textContent=`${meanStrength} kn`;$('raceSetup').hidden=false;$('lapCount').focus?.();$('lapCount').select?.();}
$('reset').addEventListener('click',openRaceSetup);$('resultsRestart').addEventListener('click',openRaceSetup);$('raceSetupCancel').addEventListener('click',()=>{$('raceSetup').hidden=true});$('raceSetupForm').addEventListener('submit',e=>{e.preventDefault();const count=Number($('lapCount').value);if(!Number.isInteger(count)||count<1||count>99)return;const wind=Number($('strength').value);if(!Number.isFinite(wind)||wind<0||wind>25)return;const choice=$('courseType').value;if(!COURSE_TYPES.includes(choice))return;const daylight=$('timeOfDay').value;if(!DAYLIGHT[daylight])return;timeOfDay=daylight;atmosphere.set(timeOfDay);updateNavigationLights();try{window.localStorage?.setItem('regatta-daylight',timeOfDay)}catch{}courseChoice=choice;meanStrength=wind;raceLaps=count;try{window.localStorage?.setItem('regatta-laps',String(count))}catch{}$('raceSetup').hidden=true;armStartAudio();restartGame();updateRaceBoard()});
function updateHistory(){for(const [i,name]of HISTORY_BOATS.entries())for(let place=0;place<6;place++)$(`history${i}${place}`).textContent=String(finishHistory.counts[name][place]);$('historySummary').textContent=`${finishHistory.races} race${finishHistory.races===1?'':'s'} · ${finishHistory.persistent?'saved in this browser':'this session'}`;}
$('resetHistory').addEventListener('click',()=>{finishHistory.reset();updateHistory()});
function updateResults(){const show=race.stage==='finished'&&!mooringMode;$('raceResults').hidden=!show;if(!show)return;if(!race.historyRecorded&&finishHistory.record([playerRace,...fleet]))race.historyRecorded=true;updateHistory();const results=raceResults(race,[playerRace,...fleet]);for(const [i,r]of results.entries()){$(`resultPlace${i}`).textContent=String(r.place);$(`resultName${i}`).textContent=r.name;$(`resultTime${i}`).textContent=r.time;$(`resultState${i}`).textContent=r.finished?'Finished':'Unfinished at race end';}}
function updateMooringMusic(){mooringMusic?.stop();mooringMusic=null;if(mooringMode&&mooringMusicEnabled&&!document.hidden){armStartAudio();mooringMusic=startMooringMusic(startAudio)}$('mooringMusic').textContent=mooringMusicEnabled?'Music on':'Music off';$('mooringMusic').setAttribute('aria-pressed',String(mooringMusicEnabled));}
function enterMoorings(){if(!ready||race.stage!=='finished')return;if(!mooringMode){running=false;stop();mooringMode=true;mooringTime=0;mooringView ||= createMooringView(scene,[boat,...fleet.map(r=>r.root)]);mooringView.enter();boatEffects.reset();$('gameMain').classList.add('at-moorings');$('settingsPanel').hidden=true;$('mooringControls').hidden=false;for(const r of fleet){r.tag.hidden=true;r.sheetLine.visible=false}sheetLine.visible=false;for(const r of ribbons)r.mesh.visible=false;committee.visible=startLine.visible=false;for(const b of buoys)b.visible=b.userData.arc.visible=false;updateMooringMusic();resize();}$('raceResults').hidden=true;}
function leaveMoorings(){if(!mooringMode)return;mooringMode=false;mooringView.leave();mooringMusic?.stop();mooringMusic=null;$('gameMain').classList.remove('at-moorings');$('settingsPanel').hidden=false;$('mooringControls').hidden=true;sheetLine.visible=true;for(const r of fleet)r.sheetLine.visible=true;buoys.forEach((b,i)=>b.visible=b.userData.arc.visible=Boolean(course[i]));resize();}
$('resultsClose').addEventListener('click',enterMoorings);$('mooringStart').addEventListener('click',openRaceSetup);$('mooringResults').addEventListener('click',()=>{$('raceResults').hidden=false});$('mooringMusic').addEventListener('click',()=>{mooringMusicEnabled=!mooringMusicEnabled;updateMooringMusic()});document.addEventListener('visibilitychange',()=>{if(mooringMode)updateMooringMusic()});
function frame(now){requestAnimationFrame(frame);if(mooringMode){const dt=Math.min(.05,Math.max(0,(now-lastTime)/1000));lastTime=now;if(!document.hidden)mooringTime+=dt;const mooringWind=sampleWind(meanBearing,meanStrength,simTime+mooringTime,170,-216);mooringView.update(mooringTime,camera,mooringWind.direction);updateYachtClubWind(yachtClub,simTime+mooringTime,mooringWind.direction,mooringWind.strength);if(seaSurface){seaSurface.position.set(100,seaSurface.position.y,-200);seaSurface.material.userData.waterTime.value=simTime+mooringTime;seaSurface.material.normalMap.offset.set(mooringTime*.015,mooringTime*.008)}updateCoast(simTime+mooringTime);updatePassingLife(simTime+mooringTime);atmosphere.follow(camera.position);renderer.render(scene,camera);return;}const dt=running&&ready&&race.stage!=='finished'?Math.min(.05,(now-lastTime)/1000):0;const wasCountdown=race.stage==='countdown';simTime+=dt;tickRace(race,dt);if(wasCountdown&&race.stage==='racing'){flagEarlyStarts(race,[playerRace,...fleet]);playStartingGun()}lastTime=now;
 if(trimIn!==trimOut){$('sheet').value=THREE.MathUtils.clamp(Number($('sheet').value)+(trimOut?1:-1)*24*dt,5,90);labels()}
 heading=steerHeading(heading,orbitDragging?0:tiller,speed,dt);const base=state(),patches=windPatches(simTime,base.direction),localWind=sampleWind(base.direction,base.strength,simTime,boat.position.x,boat.position.z,patches),s={...base,...localWind,baseDirection:base.direction,baseStrength:base.strength,patches};updatePuffs(patches);updateCoast(simTime);updateYachtClubWind(yachtClub,simTime,s.direction,s.strength);const shadow=updateWindShadows(s.direction),motion=advanceBoat(speed,relativeWind(s.direction,heading),s.strength,s.sheet,dt,shadow,s.gust),r=motion.sail,k=1-Math.exp(-dt*3);angle+=(r.sail-angle)*k;heel+=(r.heel-heel)*(1-Math.exp(-dt*1.5));
 if(ready){const previousPosition={x:boat.position.x,z:boat.position.z},previousFleet=fleet.map(r=>({x:r.x,z:r.z}));speed=motion.speed;boat.position.y=boatBob(simTime);travel+=motion.advance;boat.position.x+=motion.advance*Math.cos(heading);boat.position.z+=motion.advance*Math.sin(heading);stepFleet(s,dt);Object.assign(playerRace,{x:boat.position.x,z:boat.position.z,heading,speed,clock:simTime});
 if(dt>0&&race.stage==='racing'){const finishes=[];for(const [i,body]of [playerRace,...fleet].entries()){const finish=scoreRaceBoat(body,race,course,i===0?previousPosition:previousFleet[i-1]);if(finish!==null)finishes.push({body,fraction:finish})}recordFinishes(race,finishes,[playerRace,...fleet],dt)}
 activeMark=playerRace.target;marksRounded=playerRace.rounded;updateStartLine();updateRaceBoard();buoys.forEach((buoy,i)=>{buoy.position.y=boatBob(simTime+i*.7)});updateMarkDial();cameraTarget.set(boat.position.x-Math.cos(heading),2.8,boat.position.z-Math.sin(heading));updateCamera();if(seaSurface){seaSurface.position.x=Math.floor(boat.position.x/100)*100;seaSurface.position.z=Math.floor(boat.position.z/100)*100;const extra=(waterSpeedGain(speed)-1)*motion.advance*.18;waterOffsetX=(waterOffsetX+extra*Math.cos(heading))%1;waterOffsetZ=(waterOffsetZ+extra*Math.sin(heading))%1;seaSurface.material.normalMap.offset.set(waterOffsetX+simTime*.015,waterOffsetZ+simTime*.008);seaSurface.material.userData.waterTime.value=simTime}}
 $('speedOut').textContent=`${(speed/KNOT).toFixed(1)} kn`;$('apparentOut').textContent=`${Math.abs(motion.apparent.direction).toFixed(0)}° / ${motion.apparent.strength.toFixed(1)} kn`;
 const noGo=noGoHalfAngle(s.strength,speed,s.gust),w=noGo*Math.PI/180,dx=43*Math.sin(w),dy=43*Math.cos(w);$('noGoSector').setAttribute('d',`M50 50 L${50-dx} ${50+dy} A43 43 0 0 0 ${50+dx} ${50+dy} Z`);$('noGoLabel').textContent=`RED: NO-GO ±${noGo.toFixed(0)}°`;
 $('trueWindSpeed').textContent=`${s.strength.toFixed(1)} kn`;$('trueWindSpeed').classList.toggle('in-puff',s.gust>.15);
 const dialAngle=windDialRotation(s.direction,heading);$('windDialArrow').setAttribute('transform',`rotate(${dialAngle} 50 50)`);const rel=relativeWind(s.direction,heading);$('windDialLabel').textContent=s.strength===0?'No true wind':Math.abs(rel)<5?'Headwind':Math.abs(rel)>175?'Wind astern':`From ${rel<0?'port':'starboard'} · ${Math.abs(rel).toFixed(0)}°`;$('windDialArrow').style.opacity=s.strength===0?'.25':'1';
 if(ready){sail.visible=!orbitDragging;updateSailFlutter(sail,angle,r.status);sail.material.color.set(shadow>.06?0xffe44d:0xfafaf3).multiplyScalar(timeOfDay==='night'?.28:1);$('shadowStatus').textContent=shadow>.06?'YELLOW SAIL · Wind shadow':'';const sailPos=sail.geometry.attributes.position;for(let i=0;i<sailPos.count;i++){const v=swingVertex(sailOriginal[i*3],sailOriginal[i*3+1],sailOriginal[i*3+2],sailPivots[i],angle*Math.PI/180);sailPos.setXYZ(i,...v)}sailPos.needsUpdate=true;sail.geometry.computeBoundingSphere();boom.rotation.y=angle*Math.PI/180;boat.rotation.order='YXZ';boat.rotation.y=-heading;boat.rotation.x=heel*Math.PI/180;boat.updateMatrixWorld(true);updateSheets(boat,sheetLine)}
 if(ready){const tt=telltaleState(r),a=angle*Math.PI/180,y=2.4,pivot=sailEdge(y),anchorX=pivot-.28,windward=Math.sign(motion.apparent.direction)||1;
 for(const ribbon of ribbons){ribbon.mesh.visible=!orbitDragging;const flutter=tt==='running'||(tt==='windward'&&ribbon.side===windward)||(tt==='leeward'&&ribbon.side!==windward);const positions=ribbon.mesh.geometry.attributes.position;const points=[];
  for(let i=0;i<=10;i++){const f=i/10,x=anchorX-.46*f;let yy=y;if(tt==='drooping')yy-=f*.42;else if(flutter)yy+=Math.sin(simTime*22+f*13+ribbon.side)*f*.14;const local=swingVertex(x,yy,0,pivot,a);local[0]+=ribbon.side*.035*Math.sin(a);local[2]+=ribbon.side*.035*Math.cos(a);points.push(sail.localToWorld(new THREE.Vector3(...local)))}
  for(let i=0;i<10;i++){const A=points[i],B=points[i+1],w=.013;const verts=[[A.x,A.y-w,A.z],[A.x,A.y+w,A.z],[B.x,B.y+w,B.z],[A.x,A.y-w,A.z],[B.x,B.y+w,B.z],[B.x,B.y-w,B.z]];verts.forEach((v,k)=>positions.setXYZ(i*6+k,...v))}positions.needsUpdate=true;ribbon.mesh.geometry.computeBoundingSphere();
 }
 $('telltaleOut').textContent=tt==='windward'?'Windward telltale fluttering':tt==='leeward'?'Leeward telltale fluttering':tt==='streaming'?'Both streaming: good trim':tt==='running'?'Downwind: telltales may flutter':'No airflow: ribbons drooping';}
 $('runStatus').textContent=race.stage==='finished'?'RACE FINISHED':running?'SAILING':mobileControls()?'PAUSED · Touch the tiller or trim pad':'PAUSED · Hover over the tiller below';$('headingOut').textContent=`${(((heading*180/Math.PI)%360+360)%360).toFixed(0).padStart(3,'0')}°`;$('tillerMarker').style.left=`${(tiller+1)*50}%`;
 $('angleOut').textContent=`${Math.abs(angle).toFixed(1)}°`;$('heelOut').textContent=`${Math.abs(heel).toFixed(1)}°`;$('status').textContent=({'Drawing':'Powered','Running':'Downwind','Over-trimmed':'Too tight'})[r.status]||r.status;const hint=trimHint(speed,relativeWind(s.direction,heading),s.strength,s.sheet,s.gust),guide=hint.startsWith('Sheet in')?['Trim in','Hold left mouse or A','adjust']:hint.startsWith('Ease out')?['Let sail out','Hold right mouse or D','adjust']:hint.startsWith('Hold trim')?['Hold this trim','Sail is set for speed','good']:hint.startsWith('Steer out')?['Turn out of the red sector','The sail needs a better wind angle','steer']:['No wind','Set more wind when starting a race','calm'];$('trimHint').textContent=guide[0];$('trimAction').textContent=mobileControls()&&guide[2]==='adjust'?(guide[0]==='Trim in'?'Hold the upper thumb button':'Hold the lower thumb button'):guide[1];$('trimHint').setAttribute('data-trim',guide[2]);
 $('windTag').textContent=`WIND FROM ${((s.direction+360)%360).toFixed(0)}° · ${s.strength.toFixed(1)} kn${s.gust>.15?' · PUFF':''}`;
 updateCourseMap(course,[{x:boat.position.x,z:boat.position.z,heading},...fleet],activeMark,s.direction,s.strength,race);

 if(ready)boatEffects.update([{x:boat.position.x,z:boat.position.z,heading,speed},...fleet],dt,s);updatePassingLife(simTime);atmosphere.follow(camera.position);renderer.render(scene,camera);
}labels();updateMarkDial();updateRaceBoard();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_sailing_conditions',description:'Set fixed true-wind bearing (0 degrees North), wind speed in knots, and sheet angle limit.',inputSchema:{type:'object',properties:{direction:{type:'number',minimum:-180,maximum:180},strength:{type:'number',minimum:0,maximum:25},sheet:{type:'number',minimum:5,maximum:90}},required:['direction','strength','sheet'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length!==3||!Number.isFinite(input.direction)||Math.abs(input.direction)>180||!Number.isFinite(input.strength)||input.strength<0||input.strength>25||!Number.isFinite(input.sheet)||input.sheet<5||input.sheet>90)throw new Error('Invalid sailing conditions');stop();meanBearing=input.direction;meanStrength=input.strength;$('sheet').value=input.sheet;labels();return state()}})).catch(()=>{})}catch{}}
