import * as THREE from './vendor/three.module.js';
import {BADGE_INKS,BADGE_SYMBOLS} from './sail-badges.js';
export function addBattleFlag(root,index){
 const mast=root.getObjectByName('Mast'),parent=mast||root,pivot=new THREE.Group();pivot.name='Masthead battle flag';pivot.visible=false;
 if(mast?.geometry){const p=mast.geometry.attributes.position;let top=-Infinity,x=0,z=0,count=0;for(let i=0;i<p.count;i++)top=Math.max(top,p.getY(i));for(let i=0;i<p.count;i++)if(p.getY(i)>top-.025){x+=p.getX(i);z+=p.getZ(i);count++}pivot.position.set(x/count,top,z/count)}else pivot.position.set(-.70,6.44,0);
 const height=2.10,width=1.45,geometry=new THREE.PlaneGeometry(width,height,18,24),positions=geometry.attributes.position,original=positions.array.slice(),uv=[];for(let i=0;i<positions.count;i++)uv.push(positions.getX(i)/.55,positions.getY(i)/.55);geometry.setAttribute('flagLogo',new THREE.Float32BufferAttribute(uv,2));
 const material=new THREE.MeshStandardMaterial({color:[0xb71e2b,0x155fc8,0xf4c72d,0x35b759,0x16191d,0xf3f2e9][index],roughness:.95,side:THREE.DoubleSide});material.onBeforeCompile=shader=>{shader.vertexShader='attribute vec2 flagLogo;varying vec2 battleLogo;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nbattleLogo=flagLogo;');shader.fragmentShader='varying vec2 battleLogo;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>\nvec2 q=battleLogo;float disk=1.0-smoothstep(.90,.94,length(q));float ring=step(.76,length(q))*disk;float symbol=(${BADGE_SYMBOLS[index]})*disk;diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.98),disk*.95);diffuseColor.rgb=mix(diffuseColor.rgb,${BADGE_INKS[index]},max(ring,symbol));`)};material.customProgramCacheKey=()=>`battle-flag-logo-${index}`;
 const flag=new THREE.Mesh(geometry,material);flag.name='Battle flag with sail logo';flag.position.set(width/2,-height/2,0);pivot.add(flag);parent.add(pivot);
 const parentRotation=new THREE.Quaternion(),worldRotation=new THREE.Quaternion(),up=new THREE.Vector3(0,1,0);
 return {pivot,flag,height,update(time,wind,strength=12){parent.getWorldQuaternion(parentRotation);worldRotation.setFromAxisAngle(up,-(wind*Math.PI/180+Math.PI));pivot.quaternion.copy(parentRotation.invert()).multiply(worldRotation);const flutter=Math.min(1,strength/8);for(let i=0;i<positions.count;i++){const x=original[i*3],y=original[i*3+1],along=(x+width/2)/width;positions.setXYZ(i,x,y+Math.sin(time*3.2+along*5+index)*along*.04*flutter,Math.sin(time*4.3+along*8+y*1.8+index*.7)*along*.17*flutter)}positions.needsUpdate=true;geometry.computeVertexNormals();geometry.computeBoundingSphere();}};
}
