import * as THREE from './vendor/three.module.js';
export const DAYLIGHT={night:{sky:0x030713,horizon:0x101a2b,sun:0x8da7dc,ground:0x09111c,power:.16,ambient:.32,exposure:.95,y:8},morning:{sky:0x769fc2,horizon:0xf2c8a2,sun:0xffd7a2,ground:0x455d71,power:2.5,ambient:2.1,exposure:1.1,y:5},midday:{sky:0x639fcc,horizon:0x97bdcd,sun:0xfff6dd,ground:0x496673,power:3,ambient:2.4,exposure:1.15,y:10},golden:{sky:0x657caa,horizon:0xf2b780,sun:0xffba72,ground:0x574b64,power:3.2,ambient:1.8,exposure:1.12,y:2.5},dusk:{sky:0x354569,horizon:0xc18c99,sun:0xff9f78,ground:0x30394f,power:1.3,ambient:1.65,exposure:1.05,y:1.1}};
export function createAtmosphere(scene,renderer,sun,ambient){
 const sky=new THREE.Mesh(new THREE.SphereGeometry(950,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color()},bottom:{value:new THREE.Color()}},vertexShader:'varying vec3 direction;void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 direction;void main(){float h=clamp(normalize(direction).y,0.,1.);gl_FragColor=vec4(mix(bottom,top,pow(h,.55)),1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));sky.name='Time of day sky';sky.frustumCulled=false;scene.add(sky);
 return {set(choice){const p=DAYLIGHT[choice]||DAYLIGHT.midday;sky.material.uniforms.top.value.set(p.sky);sky.material.uniforms.bottom.value.set(p.horizon);scene.fog.color.set(p.horizon);renderer.setClearColor(p.horizon);sun.color.set(p.sun);sun.intensity=p.power;sun.position.set(-7,p.y,6);ambient.color.set(p.horizon);ambient.groundColor.set(p.ground);ambient.intensity=p.ambient;renderer.toneMappingExposure=p.exposure},follow(position){sky.position.copy(position)}};
}
export function createBoatEffects(scene){
 // One bounded particle pool for all six boats; nothing is added per frame.
 const count=720,geo=new THREE.BufferGeometry(),positions=new Float32Array(count*3),colors=new Float32Array(count*3),particles=Array.from({length:count},()=>({life:0}));
 for(let i=0;i<count;i++)positions[i*3+1]=-20;geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));
 const foam=new THREE.Points(geo,new THREE.PointsMaterial({size:.18,color:0xe2faff,vertexColors:true,transparent:true,opacity:.65,depthWrite:false}));foam.name='Fleet wakes and bow spray';foam.frustumCulled=false;scene.add(foam);let cursor=0,accumulator=0;const previous=new Map(),trails=Array.from({length:6},()=>[]);
 const wakeGeo=new THREE.BufferGeometry(),wakeVertices=new Float32Array(6*63*12*3),wakeAlpha=new Float32Array(6*63*12);wakeGeo.setAttribute('position',new THREE.BufferAttribute(wakeVertices,3));wakeGeo.setAttribute('foamAlpha',new THREE.BufferAttribute(wakeAlpha,1));const wake=new THREE.Mesh(wakeGeo,new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,vertexShader:'attribute float foamAlpha;varying float alpha;void main(){alpha=foamAlpha;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying float alpha;void main(){gl_FragColor=vec4(.77,.94,1.,alpha);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));wake.name='Six foaming transom wakes';wake.frustumCulled=false;scene.add(wake);
 function emit(x,y,z,vx,vy,vz,life){const p=particles[cursor];Object.assign(p,{x,y,z,vx,vy,vz,life,max:life});cursor=(cursor+1)%count}
 return {reset(){wakeVertices.fill(0);wakeAlpha.fill(0);positions.fill(0);for(let i=0;i<count;i++)positions[i*3+1]=-20;colors.fill(0);wakeGeo.attributes.position.needsUpdate=true;wakeGeo.attributes.foamAlpha.needsUpdate=true;geo.attributes.position.needsUpdate=true;geo.attributes.color.needsUpdate=true;for(const p of particles)p.life=0;previous.clear();trails.forEach(t=>t.length=0);accumulator=0},update(bodies,dt,wind){if(dt<=0)return;accumulator+=dt;const bursts=Math.floor(accumulator/.055);accumulator-=bursts*.055;for(const [id,b]of bodies.entries()){const c=Math.cos(b.heading),s=Math.sin(b.heading),turn=Math.abs(Math.atan2(Math.sin(b.heading-(previous.get(id)??b.heading)),Math.cos(b.heading-(previous.get(id)??b.heading))))/Math.max(dt,.001);previous.set(id,b.heading);if(b.speed<.3)continue;for(let tick=0;tick<bursts;tick++){trails[id].unshift({x:b.x-3.55*c,z:b.z-3.55*s,heading:b.heading,age:0,speed:b.speed});if(trails[id].length>64)trails[id].pop();for(const side of [-1,1]){const spread=.55+Math.random()*.3;emit(b.x-3.55*c-side*spread*s,.09,b.z-3.55*s+side*spread*c,-c*.35-side*s*.27,0,-s*.35+side*c*.27,2.3+Math.min(2,b.speed*.3));}const energy=Math.min(1,b.speed/5)*(.15+Math.min(1,turn)*.65+(wind.gust||0)*1.4);if(Math.random()<energy)for(const side of [-1,1])emit(b.x+.25*c-side*.48*s,.15,b.z+.25*s+side*.48*c,-c*.7-side*s*.9,1+energy*1.3,-s*.7+side*c*.9,.65);}}
 let vertex=0;wakeVertices.fill(0);wakeAlpha.fill(0);for(const trail of trails){for(const p of trail)p.age+=dt;while(trail.at(-1)?.age>4)trail.pop();for(let j=0;j<trail.length-1;j++)for(const side of [-1,1]){const A=trail[j],B=trail[j+1],edge=(p,outer)=>{const width=.5+p.age*(.3+Math.min(3,p.speed)*.1)+(outer?.09:-.04);return [p.x-Math.sin(p.heading)*side*width,.10,p.z+Math.cos(p.heading)*side*width]};const a=edge(A,false),b=edge(A,true),c=edge(B,true),d=edge(B,false);for(const [point,sample]of [[a,A],[b,A],[c,B],[a,A],[c,B],[d,B]]){wakeVertices.set(point,vertex*3);wakeAlpha[vertex++]=.28*Math.max(0,1-sample.age/4)}}}wakeGeo.attributes.position.needsUpdate=true;wakeGeo.attributes.foamAlpha.needsUpdate=true;
 for(let i=0;i<count;i++){const p=particles[i];if(p.life>0){p.life=Math.max(0,p.life-dt);p.x+=p.vx*dt;p.y=Math.max(.075,p.y+p.vy*dt);p.z+=p.vz*dt;if(p.vy)p.vy-=4.5*dt;positions.set([p.x,p.y,p.z],i*3);const fade=Math.max(0,p.life/p.max);colors.set([fade*.78,fade*.95,fade],i*3)}else{positions.set([0,-20,0],i*3);colors.set([0,0,0],i*3)}}geo.attributes.position.needsUpdate=true;geo.attributes.color.needsUpdate=true}};
}
export function addPassingLife(scene){
 const birds=[];const mat=new THREE.LineBasicMaterial({color:0xf2efdf});for(let i=0;i<12;i++){const bird=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.65,0,0),new THREE.Vector3(),new THREE.Vector3(.65,0,0)]),mat);bird.name='Coastal gull';scene.add(bird);birds.push(bird)}
 const cruisers=[];for(let i=0;i<3;i++){const root=new THREE.Group(),hull=new THREE.Mesh(new THREE.SphereGeometry(1,12,6),new THREE.MeshStandardMaterial({color:[0xf4e7d6,0x7fa9b8,0xb55242][i]}));hull.scale.set(5,.65,1.3);root.add(hull);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,9,6),new THREE.MeshStandardMaterial({color:0xe8e1d5}));mast.position.y=4.5;root.add(mast);const sailGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,8,0),new THREE.Vector3(0,1,0),new THREE.Vector3(-4,1,0)]);sailGeo.setIndex([0,1,2]);sailGeo.computeVertexNormals();root.add(new THREE.Mesh(sailGeo,new THREE.MeshStandardMaterial({color:0xf3ebd4,side:THREE.DoubleSide})));root.name='Passing coastal sailboat';scene.add(root);cruisers.push(root)}
 return time=>{birds.forEach((b,i)=>{const a=time*.018+i*.52;b.position.set(175*Math.cos(a)+60,14+i*.8+Math.sin(time*.6+i),180*Math.sin(a)-50);b.rotation.y=-a;const p=b.geometry.attributes.position,flap=Math.sin(time*5+i)*.28;p.setY(0,flap);p.setY(2,flap);p.needsUpdate=true});cruisers.forEach((b,i)=>{const a=time*.002+i*2.1;b.position.set(260*Math.cos(a),.12*Math.sin(time+i),260*Math.sin(a));b.rotation.y=-a-Math.PI/2})};
}

// Local +Z is starboard. Lights remain attached through turns, heel and bobbing.
export function addNavigationLights(root){
 const group=new THREE.Group();group.name='Night navigation lights';group.visible=false;
 const n=32,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=(y*n+x)*4,r=Math.hypot((x+.5-n/2)/(n/2),(y+.5-n/2)/(n/2));data[i]=data[i+1]=data[i+2]=255;data[i+3]=Math.round(255*Math.max(0,1-r)**2)}const glow=new THREE.DataTexture(data,n,n,THREE.RGBAFormat);glow.needsUpdate=true;
 for(const [name,color,x,z]of [['White stern light',0xffffff,-3.48,0],['Red port bow light',0xff1928,.18,-.36],['Green starboard bow light',0x20ff65,.18,.36]]){
  const lamp=new THREE.Group();lamp.name=name;lamp.position.set(x,z===0?.48:.379,z);
  const bulb=new THREE.Mesh(new THREE.SphereGeometry(.065,8,6),new THREE.MeshBasicMaterial({color,toneMapped:false}));lamp.add(bulb);
  const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glow,color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));halo.scale.set(.65,.65,.65);lamp.add(halo);
  const light=new THREE.PointLight(color,2.2,5,2);light.name=name+' illumination';lamp.add(light);group.add(lamp);
 }
 root.add(group);return group;
}
