import {addBattleFlag} from './battle-flags.js';
import * as THREE from './vendor/three.module.js';
export function createMooringView(scene,roots){
 const group=new THREE.Group();group.name='Yacht club moorings';group.visible=false;scene.add(group);const records=[];
 const cloth=new THREE.MeshStandardMaterial({color:0xe6e1ce,roughness:1}),ties=new THREE.MeshStandardMaterial({color:0x4c6474,roughness:.85});
 roots.forEach((root,i)=>{const x=158+(i%3)*12,z=-216-Math.floor(i/3)*11,boom=root.getObjectByName('Boom'),bundle=new THREE.Group();bundle.name='Sail lowered and furled';bundle.visible=false;
 const roll=new THREE.Mesh(new THREE.CylinderGeometry(.105,.135,2.75,12,10),cloth);roll.rotation.z=Math.PI/2;roll.position.set(-1.37,.055,0);bundle.add(roll);
 for(let j=0;j<7;j++){const fold=new THREE.Mesh(new THREE.TorusGeometry(.12,.015,5,12),j%3===0?ties:cloth);fold.rotation.y=Math.PI/2;fold.position.set(-.20-j*.38,.055,0);bundle.add(fold)}
 const gathered=new THREE.Mesh(new THREE.CylinderGeometry(.10,.15,.34,10),cloth);gathered.position.set(-.04,.19,0);bundle.add(gathered);boom.add(bundle);
 const buoy=new THREE.Mesh(new THREE.SphereGeometry(.32,12,8),new THREE.MeshStandardMaterial({color:0xf4eee0,roughness:.65}));buoy.position.set(x,.05,z+4);group.add(buoy);
 const rope=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xb4a481}));rope.name='Mooring pennant';group.add(rope);const battle=addBattleFlag(root,i);records.push({root,boom,bundle,buoy,rope,battle,x,z,snapshot:null});});
 return {records,enter(){group.visible=true;for(const r of records){r.snapshot={position:r.root.position.clone(),rotation:r.root.rotation.clone(),boom:r.boom.rotation.clone()};r.bundle.visible=true;r.battle.pivot.visible=true;r.root.getObjectByName('Sail').visible=false;r.boom.rotation.y=0}},leave(){group.visible=false;for(const r of records){r.bundle.visible=false;r.battle.pivot.visible=false;r.root.getObjectByName('Sail').visible=true;if(r.snapshot){r.root.position.copy(r.snapshot.position);r.root.rotation.copy(r.snapshot.rotation);r.boom.rotation.copy(r.snapshot.boom)}}},update(time,camera,wind=70,strength=12){for(const [i,r]of records.entries()){const heading=wind*Math.PI/180+.035*Math.sin(time*.4+i),c=Math.cos(heading),s=Math.sin(heading),sway=.13*Math.sin(time*.37+i);r.root.position.set(r.buoy.position.x-4*c-sway*s,.07*Math.sin(time*1.6+i*.8),r.buoy.position.z-4*s+sway*c);r.root.rotation.set(.014*Math.sin(time*.9+i),-heading,.012*Math.sin(time*1.2+i),'YXZ');r.root.getObjectByName('Sail').visible=false;r.boom.rotation.y=0;r.root.updateMatrixWorld(true);r.battle.update(time,wind,strength);r.buoy.position.y=.04+.045*Math.sin(time*1.6+i*.8+.5);const bow=r.root.localToWorld(new THREE.Vector3(.82,.30,0)),anchor=r.buoy.position.clone(),mid=bow.clone().lerp(anchor,.5);mid.y=.10;r.rope.geometry.setFromPoints([bow,mid,anchor]);}
 const distance=Math.max(30,16.5/(Math.tan(camera.fov*Math.PI/360)*Math.max(.2,camera.aspect)));camera.position.set(170+2.2*Math.sin(time*.17),7.6+.6*Math.sin(time*.21),-227-distance+.6*Math.sin(time*.12));camera.lookAt(new THREE.Vector3(170+.8*Math.sin(time*.14),4.5+.25*Math.sin(time*.18),-198));}};
}
// A quiet, seamless original synth loop; no external audio downloads.
export function startMooringMusic(audio){
 if(!audio)return null;const seconds=16,n=Math.ceil(audio.sampleRate*seconds),buffer=audio.createBuffer(1,n,audio.sampleRate),data=buffer.getChannelData(0),chords=[[196,246.94,293.66],[174.61,220,261.63],[164.81,196,246.94],[174.61,220,293.66]];
 for(let i=0;i<n;i++){const t=i/audio.sampleRate,part=Math.min(3,Math.floor(t/4)),u=t%4,envelope=Math.sin(Math.PI*u/4)**2;let sample=0;for(const frequency of chords[part])sample+=Math.sin(2*Math.PI*frequency*t)*.12+Math.sin(2*Math.PI*frequency*2*t)*.025;const note=[392,440,493.88,587.33,523.25,440,392,349.23][Math.floor(t/2)%8],v=t%2;sample+=Math.sin(2*Math.PI*note*t)*.065*Math.sin(Math.PI*v/2)**2;data[i]=sample*envelope;}
 const source=audio.createBufferSource(),gain=audio.createGain();source.buffer=buffer;source.loop=true;gain.gain.setValueAtTime(.12,audio.currentTime);source.connect(gain);gain.connect(audio.destination);source.start();return {stop(){source.stop?.();source.disconnect?.();gain.disconnect?.()}};
}
